### ISSUE TITLE
How to get facial landmarks？

### ISSUE THREAD

**Issue by KleinXin** [BadToBest/EchoMimic#105]
In the demo codes, facial landmarks have already been extracted and saved as pkl files. 
However, the algorithms used to get those landmarks are not mentioned in both papers and readme.
Could you please give some advices？thx

**Comment by joytsay** [comment]
@KleinXin 
I found you can run the  `python -u demo_motion_sync.py` 
and it will create a folder named to your test image in `animation_pose.yaml ` 
e.g. if you run `python -u demo_motion_sync.py`  with no modify to the yaml
it will produce a "d" folder with all the .pkl files you need since the default image is named d.png

![image](https://github.com/user-attachments/assets/c59909e8-8673-426e-9474-69ff2e243636)

**Comment by KleinXin** [comment]
> In this paper they extracted video landmark by MediaPipe.

thx
